env:
  browser: true
  es2021: true
extends:
  - eslint-config-preact
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/ban-ts-comment": off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes: 
    - error
    - "double"
    - { "allowTemplateLiterals": true }
  semi:
    - error
    - always
